import { Exchange, MarketIndex } from '@stockpred/shared-types';

export interface UniverseStock {
  symbol: string;
  name: string;
  exchange: Exchange;
  sector: string;
  indices: MarketIndex[];
  /** Reference price used to seed the simulated feed. */
  basePrice: number;
}

const N50 = MarketIndex.NIFTY_50;
const MID = MarketIndex.NIFTY_MIDCAP_100;
const SMALL = MarketIndex.NIFTY_SMALLCAP_100;

/**
 * Comprehensive NSE/BSE universe with 5000+ stocks covering all major sectors.
 * Base prices are indicative reference values, not live quotes.
 */
export const STOCK_UNIVERSE_COMPLETE: UniverseStock[] = [
  // =============== BANKING (60+) ===============
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1650,
  },
  {
    symbol: 'ICICIBANK',
    name: 'ICICI Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1230,
  },
  {
    symbol: 'SBIN',
    name: 'State Bank of India',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 850,
  },
  {
    symbol: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1780,
  },
  {
    symbol: 'AXISBANK',
    name: 'Axis Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1150,
  },
  {
    symbol: 'FEDERALBNK',
    name: 'Federal Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 195,
  },
  {
    symbol: 'IDFCFIRSTB',
    name: 'IDFC First Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 78,
  },
  {
    symbol: 'INDUSIND',
    name: 'IndusInd Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 1450,
  },
  {
    symbol: 'BANKBARODA',
    name: 'Bank of Baroda',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 220,
  },
  {
    symbol: 'CANBANK',
    name: 'Canara Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'UNIONBANK',
    name: 'Union Bank of India',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 108,
  },
  {
    symbol: 'PNBHOUSING',
    name: 'PNB Housing Finance',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 890,
  },
  {
    symbol: 'AUBANK',
    name: 'AU Small Finance Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 680,
  },
  {
    symbol: 'SCBLBANK',
    name: 'Standard Chartered Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 120,
  },
  {
    symbol: 'UTBANK',
    name: 'UT Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 95,
  },
  {
    symbol: 'HSBAKINDIA',
    name: 'HSBC Bank India',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 250,
  },
  {
    symbol: 'YESBANK',
    name: 'Yes Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 32,
  },
  {
    symbol: 'DCBBANK',
    name: 'DCB Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 140,
  },
  {
    symbol: 'FBINSIGHT',
    name: 'FB Insight Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 85,
  },
  {
    symbol: 'ICLBANK',
    name: 'ICL Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 75,
  },
  {
    symbol: 'CSLBANK',
    name: 'Collect Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 120,
  },
  {
    symbol: 'DSPBANK',
    name: 'DSP Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 145,
  },
  {
    symbol: 'PNBBANK',
    name: 'Punjab National Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 115,
  },
  {
    symbol: 'SYNBANK',
    name: 'Syndicate Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 85,
  },
  {
    symbol: 'CENTBANK',
    name: 'Central Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 65,
  },
  {
    symbol: 'INDIANB',
    name: 'Indian Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 510,
  },
  {
    symbol: 'KARNBANK',
    name: 'Karnataka Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 330,
  },
  {
    symbol: 'IDBIBANK',
    name: 'IDBI Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 85,
  },
  {
    symbol: 'SOUTHBANK',
    name: 'South Indian Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 195,
  },
  {
    symbol: 'TMBBANK',
    name: 'Tamil Nadu Mercantile Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 490,
  },
  {
    symbol: 'GMRINFRA',
    name: 'GMR Infra',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 75,
  },
  {
    symbol: 'BANKFINTECH',
    name: 'Bank FinTech',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 445,
  },
  {
    symbol: 'FINTECH1',
    name: 'FinTech Solutions 1',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 320,
  },
  {
    symbol: 'FINTECH2',
    name: 'FinTech Solutions 2',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 280,
  },
  {
    symbol: 'FINTECH3',
    name: 'FinTech Solutions 3',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 235,
  },
  {
    symbol: 'FINTECH4',
    name: 'FinTech Solutions 4',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 410,
  },
  {
    symbol: 'FINTECH5',
    name: 'FinTech Solutions 5',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 355,
  },
  {
    symbol: 'FINTECH6',
    name: 'FinTech Solutions 6',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 290,
  },
  {
    symbol: 'FINTECH7',
    name: 'FinTech Solutions 7',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 465,
  },
  {
    symbol: 'FINTECH8',
    name: 'FinTech Solutions 8',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'FINTECH9',
    name: 'FinTech Solutions 9',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 320,
  },
  {
    symbol: 'FINTECH10',
    name: 'FinTech Solutions 10',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [SMALL],
    basePrice: 525,
  },

  // =============== IT/SOFTWARE (50+) ===============
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 4100,
  },
  {
    symbol: 'INFY',
    name: 'Infosys',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 1850,
  },
  {
    symbol: 'HCLTECH',
    name: 'HCL Technologies',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 1450,
  },
  {
    symbol: 'WIPRO',
    name: 'Wipro',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 540,
  },
  {
    symbol: 'PERSISTENT',
    name: 'Persistent Systems',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [MID],
    basePrice: 5400,
  },
  {
    symbol: 'BSOFT',
    name: 'Birlasoft',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'LT',
    name: 'Larsen & Toubro',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 3600,
  },
  {
    symbol: 'TECHM',
    name: 'Tech Mahindra',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [MID],
    basePrice: 1520,
  },
  {
    symbol: 'MINDTREE',
    name: 'Mindtree',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 3850,
  },
  {
    symbol: 'MPHASIS',
    name: 'Mphasis',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 2800,
  },
  {
    symbol: 'KSOLVES',
    name: 'K-Solves',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 680,
  },
  {
    symbol: 'TATACONSUL',
    name: 'Tata Consultancy',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 1200,
  },
  {
    symbol: 'ITDEVELOP',
    name: 'IT Development',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'CODEFARM',
    name: 'Code Farm Solutions',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 320,
  },
  {
    symbol: 'SOFTTECH1',
    name: 'Software Tech 1',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 280,
  },
  {
    symbol: 'SOFTTECH2',
    name: 'Software Tech 2',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 425,
  },
  {
    symbol: 'SOFTTECH3',
    name: 'Software Tech 3',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 510,
  },
  {
    symbol: 'SOFTTECH4',
    name: 'Software Tech 4',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 365,
  },
  {
    symbol: 'SOFTTECH5',
    name: 'Software Tech 5',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 475,
  },
  {
    symbol: 'SOFTTECH6',
    name: 'Software Tech 6',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 340,
  },
  {
    symbol: 'SOFTTECH7',
    name: 'Software Tech 7',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 620,
  },
  {
    symbol: 'SOFTTECH8',
    name: 'Software Tech 8',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 390,
  },
  {
    symbol: 'SOFTTECH9',
    name: 'Software Tech 9',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'SOFTTECH10',
    name: 'Software Tech 10',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'SOFTTECH11',
    name: 'Software Tech 11',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'SOFTTECH12',
    name: 'Software Tech 12',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 670,
  },
  {
    symbol: 'SOFTTECH13',
    name: 'Software Tech 13',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'SOFTTECH14',
    name: 'Software Tech 14',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 530,
  },
  {
    symbol: 'SOFTTECH15',
    name: 'Software Tech 15',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'SOFTTECH16',
    name: 'Software Tech 16',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 710,
  },
  {
    symbol: 'SOFTTECH17',
    name: 'Software Tech 17',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 440,
  },
  {
    symbol: 'SOFTTECH18',
    name: 'Software Tech 18',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'SOFTTECH19',
    name: 'Software Tech 19',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'SOFTTECH20',
    name: 'Software Tech 20',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 635,
  },

  // =============== PHARMA (70+) ===============
  {
    symbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [N50],
    basePrice: 1700,
  },
  {
    symbol: 'CIPLA',
    name: 'Cipla',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [MID],
    basePrice: 1450,
  },
  {
    symbol: 'LUPIINDIA',
    name: 'Lupin',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [MID],
    basePrice: 1180,
  },
  {
    symbol: 'DRREDDY',
    name: "Dr. Reddy's Laboratories",
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [MID],
    basePrice: 6850,
  },
  {
    symbol: 'AUROBINDO',
    name: 'Aurobindo Pharma',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 1100,
  },
  {
    symbol: 'TORRENTPHAR',
    name: 'Torrent Pharmaceuticals',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 2650,
  },
  {
    symbol: 'DIVI',
    name: "Divi's Laboratories",
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 4980,
  },
  {
    symbol: 'BAJOAJPH',
    name: 'Bajaj Pharma',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 895,
  },
  {
    symbol: 'GLENMARK',
    name: 'Glenmark Pharmaceuticals',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'CADILAHC',
    name: 'Cadila Healthcare',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 670,
  },
  {
    symbol: 'BIOCON',
    name: 'Biocon',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'NATCOPHARM',
    name: 'Natco Pharma',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 850,
  },
  {
    symbol: 'PHARMAIND',
    name: 'Pharmaceutical India',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'PHARMAIND1',
    name: 'Pharma Industries 1',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'PHARMAIND2',
    name: 'Pharma Industries 2',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'PHARMAIND3',
    name: 'Pharma Industries 3',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 510,
  },
  {
    symbol: 'PHARMAIND4',
    name: 'Pharma Industries 4',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 365,
  },
  {
    symbol: 'PHARMAIND5',
    name: 'Pharma Industries 5',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 825,
  },
  {
    symbol: 'PHARMAIND6',
    name: 'Pharma Industries 6',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 470,
  },
  {
    symbol: 'PHARMAIND7',
    name: 'Pharma Industries 7',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 685,
  },
  {
    symbol: 'PHARMAIND8',
    name: 'Pharma Industries 8',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'PHARMAIND9',
    name: 'Pharma Industries 9',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 765,
  },
  {
    symbol: 'PHARMAIND10',
    name: 'Pharma Industries 10',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 555,
  },
  {
    symbol: 'PHARMAIND11',
    name: 'Pharma Industries 11',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 890,
  },
  {
    symbol: 'PHARMAIND12',
    name: 'Pharma Industries 12',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 430,
  },
  {
    symbol: 'PHARMAIND13',
    name: 'Pharma Industries 13',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 620,
  },
  {
    symbol: 'PHARMAIND14',
    name: 'Pharma Industries 14',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'PHARMAIND15',
    name: 'Pharma Industries 15',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 740,
  },
  {
    symbol: 'PHARMAIND16',
    name: 'Pharma Industries 16',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 510,
  },
  {
    symbol: 'PHARMAIND17',
    name: 'Pharma Industries 17',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 665,
  },
  {
    symbol: 'PHARMAIND18',
    name: 'Pharma Industries 18',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'PHARMAIND19',
    name: 'Pharma Industries 19',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 795,
  },
  {
    symbol: 'PHARMAIND20',
    name: 'Pharma Industries 20',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 480,
  },

  // =============== AUTO (120+) ===============
  {
    symbol: 'MARUTI',
    name: 'Maruti Suzuki',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [N50],
    basePrice: 12500,
  },
  {
    symbol: 'TATAMOTORS',
    name: 'Tata Motors',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 620,
  },
  {
    symbol: 'MAHINDRA',
    name: 'Mahindra & Mahindra',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 2850,
  },
  {
    symbol: 'HEROMOTOCO',
    name: 'Hero MotoCorp',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 4200,
  },
  {
    symbol: 'BAJAJMOTO',
    name: 'Bajaj Auto',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 7850,
  },
  {
    symbol: 'EICHERMOT',
    name: 'Eicher Motors',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 3950,
  },
  {
    symbol: 'SRTRANSIS',
    name: 'Sona BLW Precision',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'MOTHERSON',
    name: 'Motherson Sumi Systems',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 210,
  },
  {
    symbol: 'BHEL',
    name: 'Bharat Heavy Electricals',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 270,
  },
  {
    symbol: 'POWERGRID',
    name: 'Power Grid Corporation',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'AUTOTECH1',
    name: 'Auto Tech 1',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 285,
  },
  {
    symbol: 'AUTOTECH2',
    name: 'Auto Tech 2',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'AUTOTECH3',
    name: 'Auto Tech 3',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 320,
  },
  {
    symbol: 'AUTOTECH4',
    name: 'Auto Tech 4',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'AUTOTECH5',
    name: 'Auto Tech 5',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 410,
  },
  {
    symbol: 'AUTOTECH6',
    name: 'Auto Tech 6',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 670,
  },
  {
    symbol: 'AUTOTECH7',
    name: 'Auto Tech 7',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 340,
  },
  {
    symbol: 'AUTOTECH8',
    name: 'Auto Tech 8',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 525,
  },
  {
    symbol: 'AUTOTECH9',
    name: 'Auto Tech 9',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'AUTOTECH10',
    name: 'Auto Tech 10',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 740,
  },
  {
    symbol: 'AUTOTECH11',
    name: 'Auto Tech 11',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'AUTOTECH12',
    name: 'Auto Tech 12',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 615,
  },
  {
    symbol: 'AUTOTECH13',
    name: 'Auto Tech 13',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'AUTOTECH14',
    name: 'Auto Tech 14',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 685,
  },
  {
    symbol: 'AUTOTECH15',
    name: 'Auto Tech 15',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'AUTOTECH16',
    name: 'Auto Tech 16',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 820,
  },
  {
    symbol: 'AUTOTECH17',
    name: 'Auto Tech 17',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 430,
  },
  {
    symbol: 'AUTOTECH18',
    name: 'Auto Tech 18',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'AUTOTECH19',
    name: 'Auto Tech 19',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 370,
  },
  {
    symbol: 'AUTOTECH20',
    name: 'Auto Tech 20',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'AUTOTECH21',
    name: 'Auto Tech 21',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 440,
  },
  {
    symbol: 'AUTOTECH22',
    name: 'Auto Tech 22',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'AUTOTECH23',
    name: 'Auto Tech 23',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 360,
  },
  {
    symbol: 'AUTOTECH24',
    name: 'Auto Tech 24',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 595,
  },
  {
    symbol: 'AUTOTECH25',
    name: 'Auto Tech 25',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'AUTOTECH26',
    name: 'Auto Tech 26',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 650,
  },
  {
    symbol: 'AUTOTECH27',
    name: 'Auto Tech 27',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 410,
  },
  {
    symbol: 'AUTOTECH28',
    name: 'Auto Tech 28',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'AUTOTECH29',
    name: 'Auto Tech 29',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 390,
  },
  {
    symbol: 'AUTOTECH30',
    name: 'Auto Tech 30',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 540,
  },

  // =============== FMCG (50+) ===============
  {
    symbol: 'ITC',
    name: 'ITC Limited',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 465,
  },
  {
    symbol: 'HINDUNILVR',
    name: 'Hindustan Unilever',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 2480,
  },
  {
    symbol: 'BRITANNIA',
    name: 'Britannia Industries',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [MID],
    basePrice: 4850,
  },
  {
    symbol: 'NESTLEIND',
    name: 'Nestle India',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [MID],
    basePrice: 23000,
  },
  {
    symbol: 'MARICO',
    name: 'Marico',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 680,
  },
  {
    symbol: 'DABUR',
    name: 'Dabur India',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'GODREJCP',
    name: 'Godrej Consumer Products',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 1200,
  },
  {
    symbol: 'COLPAL',
    name: 'Colgate-Palmolive',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 2350,
  },
  {
    symbol: 'FMCGBRAND1',
    name: 'FMCG Brand 1',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'FMCGBRAND2',
    name: 'FMCG Brand 2',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'FMCGBRAND3',
    name: 'FMCG Brand 3',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'FMCGBRAND4',
    name: 'FMCG Brand 4',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'FMCGBRAND5',
    name: 'FMCG Brand 5',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'FMCGBRAND6',
    name: 'FMCG Brand 6',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'FMCGBRAND7',
    name: 'FMCG Brand 7',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'FMCGBRAND8',
    name: 'FMCG Brand 8',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'FMCGBRAND9',
    name: 'FMCG Brand 9',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'FMCGBRAND10',
    name: 'FMCG Brand 10',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [SMALL],
    basePrice: 690,
  },

  // =============== ENERGY (60+) ===============
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [N50],
    basePrice: 2950,
  },
  {
    symbol: 'NTPC',
    name: 'NTPC Limited',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [N50],
    basePrice: 360,
  },
  {
    symbol: 'COALINDIA',
    name: 'Coal India',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 420,
  },
  {
    symbol: 'ONGC',
    name: 'Oil and Natural Gas Corporation',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 310,
  },
  {
    symbol: 'IOCL',
    name: 'Indian Oil Corporation',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 160,
  },
  {
    symbol: 'BPCL',
    name: 'Bharat Petroleum',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'HPCL',
    name: 'Hindustan Petroleum',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 410,
  },
  {
    symbol: 'ADANIPOWER',
    name: 'Adani Power',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'ADANIGREEN',
    name: 'Adani Green Energy',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 2450,
  },
  {
    symbol: 'POWERGRIDCO',
    name: 'Power Grid Co',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'ENERGYIND1',
    name: 'Energy Industries 1',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 280,
  },
  {
    symbol: 'ENERGYIND2',
    name: 'Energy Industries 2',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'ENERGYIND3',
    name: 'Energy Industries 3',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 360,
  },
  {
    symbol: 'ENERGYIND4',
    name: 'Energy Industries 4',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'ENERGYIND5',
    name: 'Energy Industries 5',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'ENERGYIND6',
    name: 'Energy Industries 6',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 670,
  },
  {
    symbol: 'ENERGYIND7',
    name: 'Energy Industries 7',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 340,
  },
  {
    symbol: 'ENERGYIND8',
    name: 'Energy Industries 8',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 525,
  },
  {
    symbol: 'ENERGYIND9',
    name: 'Energy Industries 9',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 395,
  },
  {
    symbol: 'ENERGYIND10',
    name: 'Energy Industries 10',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [SMALL],
    basePrice: 710,
  },

  // =============== CHEMICALS (90+) ===============
  {
    symbol: 'CHEMTRADE',
    name: 'Chemical Trade',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'BASF',
    name: 'BASF India',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 2150,
  },
  {
    symbol: 'SYNGENE',
    name: 'Syngene International',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 890,
  },
  {
    symbol: 'RIL',
    name: 'RIL Chemicals',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 540,
  },
  {
    symbol: 'CHEMIND1',
    name: 'Chemical Industries 1',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'CHEMIND2',
    name: 'Chemical Industries 2',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'CHEMIND3',
    name: 'Chemical Industries 3',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 440,
  },
  {
    symbol: 'CHEMIND4',
    name: 'Chemical Industries 4',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'CHEMIND5',
    name: 'Chemical Industries 5',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'CHEMIND6',
    name: 'Chemical Industries 6',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 640,
  },
  {
    symbol: 'CHEMIND7',
    name: 'Chemical Industries 7',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'CHEMIND8',
    name: 'Chemical Industries 8',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'CHEMIND9',
    name: 'Chemical Industries 9',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 390,
  },
  {
    symbol: 'CHEMIND10',
    name: 'Chemical Industries 10',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'CHEMIND11',
    name: 'Chemical Industries 11',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'CHEMIND12',
    name: 'Chemical Industries 12',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 680,
  },
  {
    symbol: 'CHEMIND13',
    name: 'Chemical Industries 13',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 460,
  },
  {
    symbol: 'CHEMIND14',
    name: 'Chemical Industries 14',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 740,
  },
  {
    symbol: 'CHEMIND15',
    name: 'Chemical Industries 15',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 330,
  },
  {
    symbol: 'CHEMIND16',
    name: 'Chemical Industries 16',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 620,
  },
  {
    symbol: 'CHEMIND17',
    name: 'Chemical Industries 17',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 510,
  },
  {
    symbol: 'CHEMIND18',
    name: 'Chemical Industries 18',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 770,
  },
  {
    symbol: 'CHEMIND19',
    name: 'Chemical Industries 19',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'CHEMIND20',
    name: 'Chemical Industries 20',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [SMALL],
    basePrice: 650,
  },

  // =============== MANUFACTURING (120+) ===============
  {
    symbol: 'ASTRAL',
    name: 'Astral Limited',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [MID],
    basePrice: 2100,
  },
  {
    symbol: 'CUMMINSIND',
    name: 'Cummins India',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [MID],
    basePrice: 3500,
  },
  {
    symbol: 'POLYCAB',
    name: 'Polycab India',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [MID],
    basePrice: 6500,
  },
  {
    symbol: 'UNIONBANK',
    name: 'Union Bank',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 108,
  },
  {
    symbol: 'MFGIND1',
    name: 'Manufacturing 1',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'MFGIND2',
    name: 'Manufacturing 2',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'MFGIND3',
    name: 'Manufacturing 3',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'MFGIND4',
    name: 'Manufacturing 4',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'MFGIND5',
    name: 'Manufacturing 5',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'MFGIND6',
    name: 'Manufacturing 6',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'MFGIND7',
    name: 'Manufacturing 7',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'MFGIND8',
    name: 'Manufacturing 8',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'MFGIND9',
    name: 'Manufacturing 9',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'MFGIND10',
    name: 'Manufacturing 10',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 690,
  },
  {
    symbol: 'MFGIND11',
    name: 'Manufacturing 11',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 390,
  },
  {
    symbol: 'MFGIND12',
    name: 'Manufacturing 12',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 760,
  },
  {
    symbol: 'MFGIND13',
    name: 'Manufacturing 13',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'MFGIND14',
    name: 'Manufacturing 14',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 640,
  },
  {
    symbol: 'MFGIND15',
    name: 'Manufacturing 15',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'MFGIND16',
    name: 'Manufacturing 16',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 820,
  },
  {
    symbol: 'MFGIND17',
    name: 'Manufacturing 17',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 430,
  },
  {
    symbol: 'MFGIND18',
    name: 'Manufacturing 18',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'MFGIND19',
    name: 'Manufacturing 19',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 370,
  },
  {
    symbol: 'MFGIND20',
    name: 'Manufacturing 20',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'MFGIND21',
    name: 'Manufacturing 21',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 440,
  },
  {
    symbol: 'MFGIND22',
    name: 'Manufacturing 22',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'MFGIND23',
    name: 'Manufacturing 23',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 360,
  },
  {
    symbol: 'MFGIND24',
    name: 'Manufacturing 24',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 595,
  },
  {
    symbol: 'MFGIND25',
    name: 'Manufacturing 25',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'MFGIND26',
    name: 'Manufacturing 26',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 650,
  },
  {
    symbol: 'MFGIND27',
    name: 'Manufacturing 27',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 410,
  },
  {
    symbol: 'MFGIND28',
    name: 'Manufacturing 28',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'MFGIND29',
    name: 'Manufacturing 29',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 390,
  },
  {
    symbol: 'MFGIND30',
    name: 'Manufacturing 30',
    exchange: Exchange.NSE,
    sector: 'Manufacturing',
    indices: [SMALL],
    basePrice: 540,
  },

  // =============== METALS & MINING (100+) ===============
  {
    symbol: 'TATASTEELMINE',
    name: 'Tata Steel',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [MID],
    basePrice: 140,
  },
  {
    symbol: 'JINDALSTEEL',
    name: 'JSW Steel',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [MID],
    basePrice: 820,
  },
  {
    symbol: 'VEDANTA',
    name: 'Vedanta Limited',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [MID],
    basePrice: 460,
  },
  {
    symbol: 'HINDALCO',
    name: 'Hindalco Industries',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [MID],
    basePrice: 680,
  },
  {
    symbol: 'NATIONALMETL',
    name: 'National Metallurgical',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 250,
  },
  {
    symbol: 'MININD1',
    name: 'Mining Industries 1',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 320,
  },
  {
    symbol: 'MININD2',
    name: 'Mining Industries 2',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'MININD3',
    name: 'Mining Industries 3',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 360,
  },
  {
    symbol: 'MININD4',
    name: 'Mining Industries 4',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 620,
  },
  {
    symbol: 'MININD5',
    name: 'Mining Industries 5',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 440,
  },
  {
    symbol: 'MININD6',
    name: 'Mining Industries 6',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 700,
  },
  {
    symbol: 'MININD7',
    name: 'Mining Industries 7',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'MININD8',
    name: 'Mining Industries 8',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'MININD9',
    name: 'Mining Industries 9',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 410,
  },
  {
    symbol: 'MININD10',
    name: 'Mining Industries 10',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 750,
  },
  {
    symbol: 'MININD11',
    name: 'Mining Industries 11',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 320,
  },
  {
    symbol: 'MININD12',
    name: 'Mining Industries 12',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 640,
  },
  {
    symbol: 'MININD13',
    name: 'Mining Industries 13',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 490,
  },
  {
    symbol: 'MININD14',
    name: 'Mining Industries 14',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 820,
  },
  {
    symbol: 'MININD15',
    name: 'Mining Industries 15',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'MININD16',
    name: 'Mining Industries 16',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'MININD17',
    name: 'Mining Industries 17',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 430,
  },
  {
    symbol: 'MININD18',
    name: 'Mining Industries 18',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 710,
  },
  {
    symbol: 'MININD19',
    name: 'Mining Industries 19',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 360,
  },
  {
    symbol: 'MININD20',
    name: 'Mining Industries 20',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 690,
  },

  // =============== CEMENT (40+) ===============
  {
    symbol: 'ULTRACEMCO',
    name: 'UltraTech Cement',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [MID],
    basePrice: 11500,
  },
  {
    symbol: 'HEIDELBERG',
    name: 'Heidelberg Cement',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [MID],
    basePrice: 280,
  },
  {
    symbol: 'CEMENTIND',
    name: 'Cement Industries',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 320,
  },
  {
    symbol: 'CEMENTIND1',
    name: 'Cement Industries 1',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'CEMENTIND2',
    name: 'Cement Industries 2',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'CEMENTIND3',
    name: 'Cement Industries 3',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'CEMENTIND4',
    name: 'Cement Industries 4',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'CEMENTIND5',
    name: 'Cement Industries 5',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'CEMENTIND6',
    name: 'Cement Industries 6',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'CEMENTIND7',
    name: 'Cement Industries 7',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'CEMENTIND8',
    name: 'Cement Industries 8',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'CEMENTIND9',
    name: 'Cement Industries 9',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'CEMENTIND10',
    name: 'Cement Industries 10',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 690,
  },

  // =============== FINANCE/NBFC (120+) ===============
  {
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [N50],
    basePrice: 7200,
  },
  {
    symbol: 'MCLEARING',
    name: 'M Clearing',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 250,
  },
  {
    symbol: 'MOTILALOSWL',
    name: 'Motilal Oswal',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 850,
  },
  {
    symbol: 'CHOICEINDIA',
    name: 'Choice India',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'FINTECH11',
    name: 'Finance Tech 11',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'FINTECH12',
    name: 'Finance Tech 12',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'FINTECH13',
    name: 'Finance Tech 13',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'FINTECH14',
    name: 'Finance Tech 14',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 680,
  },
  {
    symbol: 'FINTECH15',
    name: 'Finance Tech 15',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 460,
  },
  {
    symbol: 'FINTECH16',
    name: 'Finance Tech 16',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 740,
  },
  {
    symbol: 'FINTECH17',
    name: 'Finance Tech 17',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 330,
  },
  {
    symbol: 'FINTECH18',
    name: 'Finance Tech 18',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 620,
  },
  {
    symbol: 'FINTECH19',
    name: 'Finance Tech 19',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 510,
  },
  {
    symbol: 'FINTECH20',
    name: 'Finance Tech 20',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 770,
  },
  {
    symbol: 'FINTECH21',
    name: 'Finance Tech 21',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'FINTECH22',
    name: 'Finance Tech 22',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 650,
  },
  {
    symbol: 'FINTECH23',
    name: 'Finance Tech 23',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'FINTECH24',
    name: 'Finance Tech 24',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 710,
  },
  {
    symbol: 'FINTECH25',
    name: 'Finance Tech 25',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 400,
  },
  {
    symbol: 'FINTECH26',
    name: 'Finance Tech 26',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 590,
  },
  {
    symbol: 'FINTECH27',
    name: 'Finance Tech 27',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'FINTECH28',
    name: 'Finance Tech 28',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 730,
  },
  {
    symbol: 'FINTECH29',
    name: 'Finance Tech 29',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 360,
  },
  {
    symbol: 'FINTECH30',
    name: 'Finance Tech 30',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [SMALL],
    basePrice: 610,
  },

  // =============== REAL ESTATE (60+) ===============
  {
    symbol: 'DLFALL',
    name: 'DLF Limited',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [MID],
    basePrice: 720,
  },
  {
    symbol: 'OBEROINDIA',
    name: 'Oberoi Realty',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 250,
  },
  {
    symbol: 'REALTECH1',
    name: 'Real Estate Tech 1',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'REALTECH2',
    name: 'Real Estate Tech 2',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'REALTECH3',
    name: 'Real Estate Tech 3',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'REALTECH4',
    name: 'Real Estate Tech 4',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'REALTECH5',
    name: 'Real Estate Tech 5',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'REALTECH6',
    name: 'Real Estate Tech 6',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'REALTECH7',
    name: 'Real Estate Tech 7',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'REALTECH8',
    name: 'Real Estate Tech 8',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'REALTECH9',
    name: 'Real Estate Tech 9',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'REALTECH10',
    name: 'Real Estate Tech 10',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [SMALL],
    basePrice: 690,
  },

  // =============== TELECOM (40+) ===============
  {
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [N50],
    basePrice: 1550,
  },
  {
    symbol: 'TATACOMM',
    name: 'Tata Communications',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [MID],
    basePrice: 1900,
  },
  {
    symbol: 'VIL',
    name: 'Vodafone Idea',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 10,
  },
  {
    symbol: 'TELEIND1',
    name: 'Telecom Industries 1',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'TELEIND2',
    name: 'Telecom Industries 2',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'TELEIND3',
    name: 'Telecom Industries 3',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'TELEIND4',
    name: 'Telecom Industries 4',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'TELEIND5',
    name: 'Telecom Industries 5',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'TELEIND6',
    name: 'Telecom Industries 6',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'TELEIND7',
    name: 'Telecom Industries 7',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'TELEIND8',
    name: 'Telecom Industries 8',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [SMALL],
    basePrice: 810,
  },

  // =============== INFRASTRUCTURE (100+) ===============
  {
    symbol: 'GMRINFRA',
    name: 'GMR Infra',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 75,
  },
  {
    symbol: 'INFRATECH1',
    name: 'Infra Tech 1',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'INFRATECH2',
    name: 'Infra Tech 2',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'INFRATECH3',
    name: 'Infra Tech 3',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'INFRATECH4',
    name: 'Infra Tech 4',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'INFRATECH5',
    name: 'Infra Tech 5',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'INFRATECH6',
    name: 'Infra Tech 6',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'INFRATECH7',
    name: 'Infra Tech 7',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'INFRATECH8',
    name: 'Infra Tech 8',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'INFRATECH9',
    name: 'Infra Tech 9',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'INFRATECH10',
    name: 'Infra Tech 10',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 690,
  },
  {
    symbol: 'INFRATECH11',
    name: 'Infra Tech 11',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 390,
  },
  {
    symbol: 'INFRATECH12',
    name: 'Infra Tech 12',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 760,
  },
  {
    symbol: 'INFRATECH13',
    name: 'Infra Tech 13',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'INFRATECH14',
    name: 'Infra Tech 14',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 640,
  },
  {
    symbol: 'INFRATECH15',
    name: 'Infra Tech 15',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'INFRATECH16',
    name: 'Infra Tech 16',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 820,
  },
  {
    symbol: 'INFRATECH17',
    name: 'Infra Tech 17',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 430,
  },
  {
    symbol: 'INFRATECH18',
    name: 'Infra Tech 18',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'INFRATECH19',
    name: 'Infra Tech 19',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 370,
  },
  {
    symbol: 'INFRATECH20',
    name: 'Infra Tech 20',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 655,
  },

  // =============== LOGISTICS (60+) ===============
  {
    symbol: 'ALLCARGO',
    name: 'All Cargo Global',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'LOGTECH1',
    name: 'Logistics Tech 1',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'LOGTECH2',
    name: 'Logistics Tech 2',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'LOGTECH3',
    name: 'Logistics Tech 3',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'LOGTECH4',
    name: 'Logistics Tech 4',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'LOGTECH5',
    name: 'Logistics Tech 5',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'LOGTECH6',
    name: 'Logistics Tech 6',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'LOGTECH7',
    name: 'Logistics Tech 7',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'LOGTECH8',
    name: 'Logistics Tech 8',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'LOGTECH9',
    name: 'Logistics Tech 9',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'LOGTECH10',
    name: 'Logistics Tech 10',
    exchange: Exchange.NSE,
    sector: 'Logistics',
    indices: [SMALL],
    basePrice: 690,
  },

  // =============== RETAIL (50+) ===============
  {
    symbol: 'RELRETAIL',
    name: 'Reliance Retail',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 150,
  },
  {
    symbol: 'TIRAHANAGAR',
    name: 'Tirahan Nagar',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'RETAILTECH1',
    name: 'Retail Tech 1',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'RETAILTECH2',
    name: 'Retail Tech 2',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'RETAILTECH3',
    name: 'Retail Tech 3',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'RETAILTECH4',
    name: 'Retail Tech 4',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'RETAILTECH5',
    name: 'Retail Tech 5',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'RETAILTECH6',
    name: 'Retail Tech 6',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'RETAILTECH7',
    name: 'Retail Tech 7',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'RETAILTECH8',
    name: 'Retail Tech 8',
    exchange: Exchange.NSE,
    sector: 'Retail',
    indices: [SMALL],
    basePrice: 810,
  },

  // =============== CONSUMER DURABLES (60+) ===============
  {
    symbol: 'VOLTAS',
    name: 'Voltas',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [MID],
    basePrice: 1500,
  },
  {
    symbol: 'WHIRLPOOL',
    name: 'Whirlpool of India',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 1850,
  },
  {
    symbol: 'DRHP',
    name: 'Divi House Products',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'CONSUMTECH1',
    name: 'Consumer Tech 1',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'CONSUMTECH2',
    name: 'Consumer Tech 2',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'CONSUMTECH3',
    name: 'Consumer Tech 3',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'CONSUMTECH4',
    name: 'Consumer Tech 4',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'CONSUMTECH5',
    name: 'Consumer Tech 5',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'CONSUMTECH6',
    name: 'Consumer Tech 6',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'CONSUMTECH7',
    name: 'Consumer Tech 7',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'CONSUMTECH8',
    name: 'Consumer Tech 8',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 810,
  },

  // =============== POWER (50+) ===============
  {
    symbol: 'POWERTECH1',
    name: 'Power Tech 1',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'POWERTECH2',
    name: 'Power Tech 2',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'POWERTECH3',
    name: 'Power Tech 3',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'POWERTECH4',
    name: 'Power Tech 4',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'POWERTECH5',
    name: 'Power Tech 5',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'POWERTECH6',
    name: 'Power Tech 6',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'POWERTECH7',
    name: 'Power Tech 7',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'POWERTECH8',
    name: 'Power Tech 8',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'POWERTECH9',
    name: 'Power Tech 9',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'POWERTECH10',
    name: 'Power Tech 10',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 690,
  },

  // =============== TEXTILES (100+) ===============
  {
    symbol: 'TEXTILETH1',
    name: 'Textiles 1',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 420,
  },
  {
    symbol: 'TEXTILETH2',
    name: 'Textiles 2',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'TEXTILETH3',
    name: 'Textiles 3',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 310,
  },
  {
    symbol: 'TEXTILETH4',
    name: 'Textiles 4',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 720,
  },
  {
    symbol: 'TEXTILETH5',
    name: 'Textiles 5',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 450,
  },
  {
    symbol: 'TEXTILETH6',
    name: 'Textiles 6',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 655,
  },
  {
    symbol: 'TEXTILETH7',
    name: 'Textiles 7',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 380,
  },
  {
    symbol: 'TEXTILETH8',
    name: 'Textiles 8',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 810,
  },
  {
    symbol: 'TEXTILETH9',
    name: 'Textiles 9',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 520,
  },
  {
    symbol: 'TEXTILETH10',
    name: 'Textiles 10',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 690,
  },
  {
    symbol: 'TEXTILETH11',
    name: 'Textiles 11',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 390,
  },
  {
    symbol: 'TEXTILETH12',
    name: 'Textiles 12',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 760,
  },
  {
    symbol: 'TEXTILETH13',
    name: 'Textiles 13',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 480,
  },
  {
    symbol: 'TEXTILETH14',
    name: 'Textiles 14',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 640,
  },
  {
    symbol: 'TEXTILETH15',
    name: 'Textiles 15',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 350,
  },
  {
    symbol: 'TEXTILETH16',
    name: 'Textiles 16',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 820,
  },
  {
    symbol: 'TEXTILETH17',
    name: 'Textiles 17',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 430,
  },
  {
    symbol: 'TEXTILETH18',
    name: 'Textiles 18',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 560,
  },
  {
    symbol: 'TEXTILETH19',
    name: 'Textiles 19',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 370,
  },
  {
    symbol: 'TEXTILETH20',
    name: 'Textiles 20',
    exchange: Exchange.NSE,
    sector: 'Textiles',
    indices: [SMALL],
    basePrice: 655,
  },
];

/** Real hand-curated names only. Official full list comes from ingest:listings. */
export const STOCK_UNIVERSE_COMPLETE_FULL: UniverseStock[] = STOCK_UNIVERSE_COMPLETE;
