import { Exchange, MarketIndex } from '@stockpred/shared-types';

export interface UniverseStock {
  symbol: string;
  name: string;
  exchange: Exchange;
  sector: string;
  indices: MarketIndex[];
  /** Reference price used to seed the simulated feed. */
  basePrice: number;
}

const N50 = MarketIndex.NIFTY_50;
const MID = MarketIndex.NIFTY_MIDCAP_100;
const SMALL = MarketIndex.NIFTY_SMALLCAP_100;

/**
 * Curated NSE universe used by the seed and the simulated market feed.
 * Base prices are indicative reference values, not live quotes.
 */
export const STOCK_UNIVERSE: UniverseStock[] = [
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [N50],
    basePrice: 2950,
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 4100,
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1650,
  },
  {
    symbol: 'ICICIBANK',
    name: 'ICICI Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1230,
  },
  {
    symbol: 'INFY',
    name: 'Infosys',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 1850,
  },
  {
    symbol: 'ITC',
    name: 'ITC Limited',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 465,
  },
  {
    symbol: 'LT',
    name: 'Larsen & Toubro',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [N50],
    basePrice: 3600,
  },
  {
    symbol: 'SBIN',
    name: 'State Bank of India',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 850,
  },
  {
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [N50],
    basePrice: 1550,
  },
  {
    symbol: 'HINDUNILVR',
    name: 'Hindustan Unilever',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 2480,
  },
  {
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [N50],
    basePrice: 7200,
  },
  {
    symbol: 'ASIANPAINT',
    name: 'Asian Paints',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [N50],
    basePrice: 2900,
  },
  {
    symbol: 'MARUTI',
    name: 'Maruti Suzuki',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [N50],
    basePrice: 12500,
  },
  {
    symbol: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1780,
  },
  {
    symbol: 'AXISBANK',
    name: 'Axis Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1150,
  },
  {
    symbol: 'TITAN',
    name: 'Titan Company',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [N50],
    basePrice: 3400,
  },
  {
    symbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [N50],
    basePrice: 1700,
  },
  {
    symbol: 'NTPC',
    name: 'NTPC Limited',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [N50],
    basePrice: 360,
  },
  // TATAMOTORS is delisted on Yahoo after the 2025 CV/PV demerger; HCLTECH replaces it.
  {
    symbol: 'HCLTECH',
    name: 'HCL Technologies',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 1450,
  },
  {
    symbol: 'WIPRO',
    name: 'Wipro',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 540,
  },
  {
    symbol: 'PERSISTENT',
    name: 'Persistent Systems',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [MID],
    basePrice: 5400,
  },
  {
    symbol: 'ASTRAL',
    name: 'Astral Limited',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 2100,
  },
  {
    symbol: 'CUMMINSIND',
    name: 'Cummins India',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 3500,
  },
  {
    symbol: 'FEDERALBNK',
    name: 'Federal Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 195,
  },
  {
    symbol: 'IDFCFIRSTB',
    name: 'IDFC First Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 78,
  },
  {
    symbol: 'POLYCAB',
    name: 'Polycab India',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 6500,
  },
  {
    symbol: 'TATACOMM',
    name: 'Tata Communications',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [MID],
    basePrice: 1900,
  },
  {
    symbol: 'VOLTAS',
    name: 'Voltas',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [MID],
    basePrice: 1500,
  },
  {
    symbol: 'CDSL',
    name: 'Central Depository Services',
    exchange: Exchange.NSE,
    sector: 'Financial Services',
    indices: [SMALL],
    basePrice: 1450,
  },
  {
    symbol: 'RADICO',
    name: 'Radico Khaitan',
    exchange: Exchange.NSE,
    sector: 'Beverages',
    indices: [SMALL],
    basePrice: 1850,
  },
  {
    symbol: 'BSOFT',
    name: 'Birlasoft',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'KFINTECH',
    name: 'KFin Technologies',
    exchange: Exchange.NSE,
    sector: 'Financial Services',
    indices: [SMALL],
    basePrice: 1050,
  },
  {
    symbol: 'CAMS',
    name: 'Computer Age Management Services',
    exchange: Exchange.NSE,
    sector: 'Financial Services',
    indices: [SMALL],
    basePrice: 4200,
  },
];
