import { Exchange, MarketIndex } from '@stockpred/shared-types';

export interface UniverseStock {
  symbol: string;
  name: string;
  exchange: Exchange;
  sector: string;
  indices: MarketIndex[];
  basePrice: number;
}

const N50 = MarketIndex.NIFTY_50;
const MID = MarketIndex.NIFTY_MIDCAP_100;
const SMALL = MarketIndex.NIFTY_SMALLCAP_100;

/**
 * EXPANDED NSE/BSE universe - all major stocks (100+).
 * Generated: 2026-06-07
 * To activate: STOCK_UNIVERSE_MODE=full-universe npm run start:all
 *
 * Note: This is a curated list of 100+ most liquid/important stocks.
 * For a complete NSE/BSE list of 2000+, run: npx ts-node scripts/fetch-all-stocks.ts
 */
export const STOCK_UNIVERSE: UniverseStock[] = [
  // NIFTY 50 + Additional Popular
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [N50],
    basePrice: 2950,
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 4100,
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1650,
  },
  {
    symbol: 'ICICIBANK',
    name: 'ICICI Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1230,
  },
  {
    symbol: 'INFY',
    name: 'Infosys',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 1850,
  },
  {
    symbol: 'ITC',
    name: 'ITC Limited',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 465,
  },
  {
    symbol: 'LT',
    name: 'Larsen & Toubro',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [N50],
    basePrice: 3600,
  },
  {
    symbol: 'SBIN',
    name: 'State Bank of India',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 850,
  },
  {
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [N50],
    basePrice: 1550,
  },
  {
    symbol: 'HINDUNILVR',
    name: 'Hindustan Unilever',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 2480,
  },
  {
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [N50],
    basePrice: 7200,
  },
  {
    symbol: 'ASIANPAINT',
    name: 'Asian Paints',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [N50],
    basePrice: 2900,
  },
  {
    symbol: 'MARUTI',
    name: 'Maruti Suzuki',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [N50],
    basePrice: 12500,
  },
  {
    symbol: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1780,
  },
  {
    symbol: 'AXISBANK',
    name: 'Axis Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [N50],
    basePrice: 1150,
  },
  {
    symbol: 'TITAN',
    name: 'Titan Company',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [N50],
    basePrice: 3400,
  },
  {
    symbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [N50],
    basePrice: 1700,
  },
  {
    symbol: 'NTPC',
    name: 'NTPC Limited',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [N50],
    basePrice: 360,
  },
  {
    symbol: 'HCLTECH',
    name: 'HCL Technologies',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 1450,
  },
  {
    symbol: 'WIPRO',
    name: 'Wipro',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 540,
  },
  // NIFTY MIDCAP 100
  {
    symbol: 'PERSISTENT',
    name: 'Persistent Systems',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [MID],
    basePrice: 5400,
  },
  {
    symbol: 'ASTRAL',
    name: 'Astral Limited',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 2100,
  },
  {
    symbol: 'CUMMINSIND',
    name: 'Cummins India',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 3500,
  },
  {
    symbol: 'FEDERALBNK',
    name: 'Federal Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 195,
  },
  {
    symbol: 'IDFCFIRSTB',
    name: 'IDFC First Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 78,
  },
  {
    symbol: 'POLYCAB',
    name: 'Polycab India',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 6500,
  },
  {
    symbol: 'TATACOMM',
    name: 'Tata Communications',
    exchange: Exchange.NSE,
    sector: 'Telecom',
    indices: [MID],
    basePrice: 1900,
  },
  {
    symbol: 'VOLTAS',
    name: 'Voltas',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [MID],
    basePrice: 1500,
  },
  {
    symbol: 'CDSL',
    name: 'Central Depository Services',
    exchange: Exchange.NSE,
    sector: 'Financial Services',
    indices: [SMALL],
    basePrice: 1450,
  },
  {
    symbol: 'RADICO',
    name: 'Radico Khaitan',
    exchange: Exchange.NSE,
    sector: 'Beverages',
    indices: [SMALL],
    basePrice: 1850,
  },
  {
    symbol: 'BSOFT',
    name: 'Birlasoft',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [SMALL],
    basePrice: 580,
  },
  {
    symbol: 'KFINTECH',
    name: 'KFin Technologies',
    exchange: Exchange.NSE,
    sector: 'Financial Services',
    indices: [SMALL],
    basePrice: 1050,
  },
  {
    symbol: 'CAMS',
    name: 'Computer Age Management Services',
    exchange: Exchange.NSE,
    sector: 'Financial Services',
    indices: [SMALL],
    basePrice: 4200,
  },
  // Additional popular stocks
  {
    symbol: 'ADANIPORTS',
    name: 'Adani Ports',
    exchange: Exchange.NSE,
    sector: 'Ports & Services',
    indices: [N50],
    basePrice: 850,
  },
  {
    symbol: 'BAJAJ-AUTO',
    name: 'Bajaj Auto',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [N50],
    basePrice: 6800,
  },
  {
    symbol: 'BPCL',
    name: 'Bharat Petroleum',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [N50],
    basePrice: 380,
  },
  {
    symbol: 'BRITANNIA',
    name: 'Britannia Industries',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 4600,
  },
  {
    symbol: 'CIPLA',
    name: 'Cipla',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [N50],
    basePrice: 1280,
  },
  {
    symbol: 'COALINDIA',
    name: 'Coal India',
    exchange: Exchange.NSE,
    sector: 'Mining',
    indices: [N50],
    basePrice: 420,
  },
  {
    symbol: 'DRREDDY',
    name: "Dr. Reddy's Laboratories",
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [N50],
    basePrice: 4700,
  },
  {
    symbol: 'EICHERMOT',
    name: 'Eicher Motors',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [N50],
    basePrice: 3800,
  },
  {
    symbol: 'GAIL',
    name: 'GAIL (India)',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [N50],
    basePrice: 180,
  },
  {
    symbol: 'GRASIM',
    name: 'Grasim Industries',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [N50],
    basePrice: 2200,
  },
  {
    symbol: 'HDFCLIFE',
    name: 'HDFC Life Insurance',
    exchange: Exchange.NSE,
    sector: 'Insurance',
    indices: [N50],
    basePrice: 580,
  },
  {
    symbol: 'HEROMOTOCO',
    name: 'Hero MotoCorp',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [N50],
    basePrice: 4200,
  },
  {
    symbol: 'HINDALCO',
    name: 'Hindalco Industries',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [N50],
    basePrice: 820,
  },
  {
    symbol: 'ICICIPRULI',
    name: 'ICICI Prudential Life',
    exchange: Exchange.NSE,
    sector: 'Insurance',
    indices: [N50],
    basePrice: 480,
  },
  {
    symbol: 'IOLCP',
    name: 'IOL Chemicals',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [MID],
    basePrice: 900,
  },
  {
    symbol: 'JSWSTEEL',
    name: 'JSW Steel',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [N50],
    basePrice: 870,
  },
  {
    symbol: 'NESTLEIND',
    name: 'Nestlé India',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [N50],
    basePrice: 23500,
  },
  {
    symbol: 'ONGC',
    name: 'Oil and Natural Gas Corporation',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [N50],
    basePrice: 320,
  },
  {
    symbol: 'POWERGRID',
    name: 'Power Grid Corporation',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [N50],
    basePrice: 290,
  },
  {
    symbol: 'SHREECEM',
    name: 'Shree Cement',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [N50],
    basePrice: 25000,
  },
  {
    symbol: 'TATAMOTORS',
    name: 'Tata Motors',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [N50],
    basePrice: 1050,
  },
  {
    symbol: 'TATAPOWER',
    name: 'Tata Power',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [N50],
    basePrice: 380,
  },
  {
    symbol: 'TATASTEEL',
    name: 'Tata Steel',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [N50],
    basePrice: 1420,
  },
  {
    symbol: 'TECHM',
    name: 'Tech Mahindra',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [N50],
    basePrice: 1650,
  },
  {
    symbol: 'TORNTPHARM',
    name: 'Torrent Pharmaceuticals',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [N50],
    basePrice: 2850,
  },
  {
    symbol: 'ULTRACEMCO',
    name: 'UltraTech Cement',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [N50],
    basePrice: 10800,
  },
  {
    symbol: 'UPL',
    name: 'UPL Limited',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [N50],
    basePrice: 680,
  },
  {
    symbol: 'ADANIGREEN',
    name: 'Adani Green Energy',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 3200,
  },
  {
    symbol: 'ADANIENT',
    name: 'Adani Enterprises',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 2850,
  },
  {
    symbol: 'APOLLOHOSP',
    name: 'Apollo Hospitals',
    exchange: Exchange.NSE,
    sector: 'Healthcare',
    indices: [MID],
    basePrice: 6500,
  },
  {
    symbol: 'ATUL',
    name: 'Atul Limited',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [MID],
    basePrice: 8900,
  },
  {
    symbol: 'AUBANK',
    name: 'AU Small Finance Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 780,
  },
  {
    symbol: 'BERGEPAINT',
    name: 'Berger Paints India',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [MID],
    basePrice: 480,
  },
  {
    symbol: 'BHARATFORG',
    name: 'Bharat Forge',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 950,
  },
  {
    symbol: 'BIOCON',
    name: 'Biocon Limited',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [MID],
    basePrice: 350,
  },
  {
    symbol: 'BOSCHLTD',
    name: 'Bosch Limited',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 25900,
  },
  {
    symbol: 'CCINDIA',
    name: 'Cholamandalam Investment',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [MID],
    basePrice: 920,
  },
  {
    symbol: 'DABUR',
    name: 'Dabur India',
    exchange: Exchange.NSE,
    sector: 'FMCG',
    indices: [MID],
    basePrice: 620,
  },
  {
    symbol: 'DEEPAKFERT',
    name: 'Deepak Fertilisers',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [MID],
    basePrice: 820,
  },
  {
    symbol: 'DELTACORP',
    name: 'Delta Corp Limited',
    exchange: Exchange.NSE,
    sector: 'Entertainment',
    indices: [SMALL],
    basePrice: 195,
  },
  {
    symbol: 'ESCORT',
    name: 'Escorts Kubota',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 2950,
  },
  {
    symbol: 'EXIDEIND',
    name: 'Exide Industries',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [MID],
    basePrice: 180,
  },
  {
    symbol: 'FORTISHEALTH',
    name: 'Fortis Healthcare',
    exchange: Exchange.NSE,
    sector: 'Healthcare',
    indices: [MID],
    basePrice: 560,
  },
  {
    symbol: 'GICRE',
    name: 'General Insurance Corporation',
    exchange: Exchange.NSE,
    sector: 'Insurance',
    indices: [MID],
    basePrice: 380,
  },
  {
    symbol: 'GMRINFRA',
    name: 'GMR Infrastructure',
    exchange: Exchange.NSE,
    sector: 'Ports & Services',
    indices: [MID],
    basePrice: 79,
  },
  {
    symbol: 'GUJGASLTD',
    name: 'Gujarat Gas Limited',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 595,
  },
  {
    symbol: 'HDFCAMC',
    name: 'HDFC Asset Management',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [MID],
    basePrice: 4150,
  },
  {
    symbol: 'HDFC',
    name: 'Housing Development Finance',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [N50],
    basePrice: 2950,
  },
  {
    symbol: 'HINDPETRO',
    name: 'Hindustan Petroleum',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 330,
  },
  {
    symbol: 'IBREALEST',
    name: 'IRB Infrastructure',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [MID],
    basePrice: 40,
  },
  {
    symbol: 'IFBIND',
    name: 'IFB Industries',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 950,
  },
  {
    symbol: 'INDHOTEL',
    name: 'Indian Hotels Company',
    exchange: Exchange.NSE,
    sector: 'Hospitality',
    indices: [MID],
    basePrice: 110,
  },
  {
    symbol: 'INDIAMART',
    name: 'IndiaMART InterMESH',
    exchange: Exchange.NSE,
    sector: 'E-Commerce',
    indices: [MID],
    basePrice: 3100,
  },
  {
    symbol: 'INDIANB',
    name: 'Indian Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 400,
  },
  {
    symbol: 'INDIGO',
    name: 'IndiGo',
    exchange: Exchange.NSE,
    sector: 'Aviation',
    indices: [MID],
    basePrice: 4100,
  },
  {
    symbol: 'INDUSINDBK',
    name: 'IndusInd Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 1600,
  },
  {
    symbol: 'JBCHOT',
    name: 'Jaiprakash Associates',
    exchange: Exchange.NSE,
    sector: 'Infrastructure',
    indices: [SMALL],
    basePrice: 18,
  },
  {
    symbol: 'JINDALSTEL',
    name: 'Jindal Steel & Power',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [MID],
    basePrice: 840,
  },
  {
    symbol: 'JPPOWER',
    name: 'Jaiprakash Power Ventures',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [SMALL],
    basePrice: 2,
  },
  {
    symbol: 'LTI',
    name: 'L&T Technology Services',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [MID],
    basePrice: 5200,
  },
  {
    symbol: 'LUPIN',
    name: 'Lupin Limited',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [MID],
    basePrice: 1950,
  },
  {
    symbol: 'MAXHEALTH',
    name: 'Max Healthcare Institute',
    exchange: Exchange.NSE,
    sector: 'Healthcare',
    indices: [MID],
    basePrice: 1150,
  },
  {
    symbol: 'METROPOLIS',
    name: 'Metropolis Healthcare',
    exchange: Exchange.NSE,
    sector: 'Healthcare',
    indices: [MID],
    basePrice: 1800,
  },
  {
    symbol: 'MFSL',
    name: 'Max Financial Services',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [MID],
    basePrice: 1050,
  },
  {
    symbol: 'MINDTREE',
    name: 'Mindtree Limited',
    exchange: Exchange.NSE,
    sector: 'IT',
    indices: [MID],
    basePrice: 4450,
  },
  {
    symbol: 'MRPL',
    name: 'Mangalore Refinery',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 130,
  },
  {
    symbol: 'MUTHOOTFIN',
    name: 'Muthoot Finance',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [MID],
    basePrice: 1650,
  },
  {
    symbol: 'NATIONALUM',
    name: 'National Aluminium Company',
    exchange: Exchange.NSE,
    sector: 'Metals & Mining',
    indices: [SMALL],
    basePrice: 80,
  },
  {
    symbol: 'NAVINFLUOR',
    name: 'Navin Fluorine International',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [MID],
    basePrice: 5200,
  },
  {
    symbol: 'OBEROIRLTY',
    name: 'Oberoi Realty',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [MID],
    basePrice: 220,
  },
  {
    symbol: 'PETRONET',
    name: 'Petronet LNG Limited',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 290,
  },
  {
    symbol: 'PFIZER',
    name: 'Pfizer Limited',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 4800,
  },
  {
    symbol: 'PHILIPLTD',
    name: 'Philips India Limited',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 1080,
  },
  {
    symbol: 'PIIND',
    name: 'Piramal Enterprises Limited',
    exchange: Exchange.NSE,
    sector: 'Chemicals',
    indices: [MID],
    basePrice: 3680,
  },
  {
    symbol: 'PRESTIGE',
    name: 'Prestige Group',
    exchange: Exchange.NSE,
    sector: 'Real Estate',
    indices: [MID],
    basePrice: 850,
  },
  {
    symbol: 'RAMCOCEM',
    name: 'The Ramco Cements Limited',
    exchange: Exchange.NSE,
    sector: 'Cement',
    indices: [SMALL],
    basePrice: 1050,
  },
  {
    symbol: 'RECLTD',
    name: 'REC Limited',
    exchange: Exchange.NSE,
    sector: 'Power',
    indices: [MID],
    basePrice: 180,
  },
  {
    symbol: 'REDINGTON',
    name: 'Redington (India) Limited',
    exchange: Exchange.NSE,
    sector: 'Distribution',
    indices: [SMALL],
    basePrice: 195,
  },
  {
    symbol: 'SANSERA',
    name: 'Sansera Engineering Limited',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 650,
  },
  {
    symbol: 'SBICARD',
    name: 'SBI Cards and Payment Systems',
    exchange: Exchange.NSE,
    sector: 'Finance',
    indices: [MID],
    basePrice: 650,
  },
  {
    symbol: 'SBILIFE',
    name: 'SBI Life Insurance Company',
    exchange: Exchange.NSE,
    sector: 'Insurance',
    indices: [N50],
    basePrice: 1650,
  },
  {
    symbol: 'SCHAEFFLER',
    name: 'Schaeffler India Limited',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 4500,
  },
  {
    symbol: 'SHARDAMOTR',
    name: 'Sharda Motor Industries',
    exchange: Exchange.NSE,
    sector: 'Auto',
    indices: [SMALL],
    basePrice: 145,
  },
  {
    symbol: 'SIEMENS',
    name: 'Siemens Limited',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [MID],
    basePrice: 6800,
  },
  {
    symbol: 'SOUTHBANK',
    name: 'South Indian Bank',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 35,
  },
  {
    symbol: 'SPARC',
    name: 'Sparc Limited',
    exchange: Exchange.NSE,
    sector: 'Pharma',
    indices: [SMALL],
    basePrice: 980,
  },
  {
    symbol: 'SUTLEJTEX',
    name: 'Sutlej Textiles and Industries',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [SMALL],
    basePrice: 15,
  },
  {
    symbol: 'SUZLON',
    name: 'Suzlon Energy Limited',
    exchange: Exchange.NSE,
    sector: 'Energy',
    indices: [MID],
    basePrice: 32,
  },
  {
    symbol: 'TVTODAY',
    name: 'TV Today Network Limited',
    exchange: Exchange.NSE,
    sector: 'Media',
    indices: [SMALL],
    basePrice: 48,
  },
  {
    symbol: 'TRENT',
    name: 'Trent Limited',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [MID],
    basePrice: 6400,
  },
  {
    symbol: 'TRIVENI',
    name: 'Triveni Engineering & Industries',
    exchange: Exchange.NSE,
    sector: 'Industrials',
    indices: [SMALL],
    basePrice: 265,
  },
  {
    symbol: 'UNIONBANK',
    name: 'Union Bank of India',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 65,
  },
  {
    symbol: 'VIPIND',
    name: 'VIP Industries Limited',
    exchange: Exchange.NSE,
    sector: 'Consumer',
    indices: [SMALL],
    basePrice: 700,
  },
  {
    symbol: 'WHIRLPOOL',
    name: 'Whirlpool of India Limited',
    exchange: Exchange.NSE,
    sector: 'Consumer Durables',
    indices: [SMALL],
    basePrice: 1900,
  },
  {
    symbol: 'YESBANK',
    name: 'Yes Bank Limited',
    exchange: Exchange.NSE,
    sector: 'Banking',
    indices: [MID],
    basePrice: 25,
  },
  {
    symbol: 'ZEEL',
    name: 'Zee Entertainment Enterprises',
    exchange: Exchange.NSE,
    sector: 'Media',
    indices: [SMALL],
    basePrice: 335,
  },
];
