apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stockpred
  namespace: stockpred
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600' # Socket.IO
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  ingressClassName: nginx
  rules:
    - host: stockpred.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: { name: api-gateway, port: { number: 3000 } }
          - path: /socket.io
            pathType: Prefix
            backend:
              service: { name: api-gateway, port: { number: 3000 } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: frontend, port: { number: 80 } }
